name: Test Raspberry PI QEMU Docker File

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  PACKAGE_NAME: my-test-packaged
  bashPass:   \033[32;1mPASSED -
  bashInfo:   \033[33;1mINFO -
  bashFail:   \033[31;1mFAILED -
  bashEnd:    \033[0m

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            setup: QEMU
            c_compiler: arm-none-eabi-gcc
            cpp_compiler: arm-none-eabi-g++
            build_type: Debug

    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        if: ${{ matrix.os == 'ubuntu-22.04' && matrix.setup == 'QEMU' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - env:
          stepName: Download QEMU Dependencies
        name: ${{ env.stepName }}
        if: ${{ matrix.os == 'ubuntu-22.04' && matrix.setup == 'QEMU' }}
        run: |
          # ${{ env.stepName }}
          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName}} ${{ env.bashEnd }}"
          sudo apt-get install -y qemu-system-aarch64 sshpass
          echo -e "::endgroup::"

      - env:
          stepName: Set up QEMU Image
        name: ${{ env.stepName }}
        if: ${{ matrix.os == 'ubuntu-22.04' && matrix.setup == 'QEMU' }}
        run: |
          # ${{ env.stepName }}
          echo -e "::group::${{ env.bashInfo }}  ${{ env.stepName }} ${{ env.bashEnd }}"
          docker pull stawiski/qemu-raspberrypi-3b:2023-05-03-raspios-bullseye-arm64
          echo -e "::endgroup::"

      - env:
          stepName: Set up QEMU build
        name: ${{ env.stepName }}
        if: ${{ matrix.os == 'ubuntu-22.04' && matrix.setup == 'QEMU' }}
        run: |
          # ${{ env.stepName }}
          # echo -e "::group::${{ env.bashInfo }} Launch Qemu ${{ env.bashEnd }}"
          echo -e "About to run the qemu command"
          docker run -it --rm -p 2222:2222 stawiski/qemu-raspberrypi-3b:2023-05-03-raspios-bullseye-arm64s
          echo -e "Past the build command"
          sshpass -p raspberry ssh -p 2222 pi@localhost
